#
# $Id: Makefile 26 2006-02-04 15:44:44Z nicb $
##
TOP=../..
PLUGIN=window~
TARGET=$(PLUGIN).pd_linux
OBJS=$(PLUGIN).o

all:	$(TARGET)

clean:
	$(RM) $(OBJS) $(TARGET)

include $(TOP)/Makefile.common
