#
# $Id: Makefile 49 2006-06-01 13:11:16Z nicb $
##
TOP=../..
PLUGIN=ltas~
TARGET=$(PLUGIN).pd_linux
OBJS=$(PLUGIN).o

all:	$(TARGET)

clean:
	$(RM) $(OBJS) $(TARGET)

include $(TOP)/Makefile.common
CFLAGS += -g
